### ISSUE TITLE
Think about if or how we aim to support `spotify_stats` (followers, listeners, streams)

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/GermanTechPodcasts#165]
In https://github.com/EngineeringKiosk/GermanTechPodcasts/pull/161, @djungowski added the following

```yaml
spotify_stats:
  followers: 5092
  listeners: 10300
  streams: 67592
  updated: "2022-12-28"
```

We don't support this yet; however, we should consider if we want to support this for a more open podcast system.

An additional question: Are we able to pull the data from the Spotify API?
